language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t desmond1999d/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true desmond1999d/docker-react npm run test